# Generated by Django 4.0.4 on 2022-06-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=128, null=True, verbose_name='Название картинки')),
                ('image', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=128, null=True, verbose_name='Кратко тема(чтоб не запутаться)')),
                ('man_text', models.TextField(blank=True, null=True, verbose_name='Текст с мужскими окончаниями')),
                ('woman_text', models.TextField(blank=True, null=True, verbose_name='Текст с женскими окончаниями')),
                ('common_text', models.TextField(blank=True, null=True, verbose_name='Общий для всех текст')),
            ],
        ),
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=128, null=True, verbose_name='Никнейм пользователя')),
                ('sex', models.BooleanField(blank=True, null=True, verbose_name='Пол (Мужской-1, Женский-0) пользователя')),
                ('tg_id', models.IntegerField(verbose_name='Уникальный ИД телеграмма')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст пользователя')),
                ('course_name', models.TextField(blank=True, max_length=128, null=True, verbose_name='Название курса')),
                ('education_start', models.DateField(auto_now_add=True, null=True, verbose_name='Время начала обучения')),
                ('education_end', models.DateField(blank=True, null=True, verbose_name='Предполагаемы конец обучения')),
                ('remind_next', models.DateField(default=86400, verbose_name='Следующее напоминание')),
                ('remind_interval_in_day', models.IntegerField(default=0, verbose_name='В какой день напоминать?')),
                ('percent_complete', models.IntegerField(default=0, verbose_name='% выполнения цели')),
                ('education_rate', models.TextField(blank=True, null=True, verbose_name='Оценка уровня обучения')),
                ('hapiness_level', models.TextField(blank=True, null=True, verbose_name='Оценка удовольствия от обучения')),
                ('what_for', models.TextField(blank=True, null=True, verbose_name='Зачем тебе этому учиться')),
                ('what_you_want', models.TextField(blank=True, null=True, verbose_name='Что ты хочешь от обучения')),
                ('what_changed', models.TextField(blank=True, null=True, verbose_name='Что в твоей жизни изменится после обучения?')),
                ('main_target', models.TextField(blank=True, null=True, verbose_name='Основная цель -задача')),
                ('smart', models.TextField(blank=True, null=True, verbose_name='SMART критерии через запятую')),
                ('period', models.DateField(blank=True, default=86400, null=True, verbose_name='Cколько времени готов потратить на подцель')),
            ],
        ),
    ]
