# Generated by Django 4.0.4 on 2022-05-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
