# Generated by Django 4.0.4 on 2022-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст пользователя'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='period',
            field=models.DateField(blank=True, null=True, verbose_name='Cколько времени готов потратить на подцель'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='remind_interval_in_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='В какой день напоминать?'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='remind_next',
            field=models.DateField(blank=True, null=True, verbose_name='Следующее напоминание'),
        ),
    ]
