# Generated by Django 4.0.4 on 2022-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectmodel_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=128, null=True, unique=True)),
                ('first_name', models.TextField(blank=True, max_length=70, null=True)),
                ('last_name', models.TextField(blank=True, max_length=70, null=True)),
                ('patronymic', models.TextField(blank=True, max_length=70, null=True)),
                ('sex', models.BooleanField(blank=True, null=True)),
                ('tg_id', models.IntegerField(unique=True)),
                ('tg_username', models.TextField(unique=True)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
