# Generated by Django 4.0.4 on 2022-06-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usertelegram_education_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='smart',
            field=models.TextField(blank=True, null=True, verbose_name='SMART критерии через @!'),
        ),
        migrations.CreateModel(
            name='HappinessStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotional_week', models.TextField(blank=True, null=True, verbose_name='Эмоции на неделю')),
                ('regularity_week', models.TextField(blank=True, null=True, verbose_name='Регулярность на неделю')),
                ('motivation_week', models.TextField(blank=True, null=True, verbose_name='уровень мотивации')),
                ('emotional_month', models.TextField(blank=True, null=True, verbose_name='Общий для всех текст')),
                ('regularity_month', models.TextField(blank=True, null=True, verbose_name='Общий для всех текст')),
                ('motivation_month', models.TextField(blank=True, null=True, verbose_name='Общий для всех текст')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usertelegram')),
            ],
        ),
    ]
