# Generated by Django 4.0.4 on 2022-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usertelegram_delete_projectmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertelegram',
            name='tg_username',
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='name',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
