# Generated by Django 4.0.4 on 2022-06-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usertelegram_tg_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='tg_id',
            field=models.IntegerField(),
        ),
    ]
