# Generated by Django 4.0.4 on 2022-06-10 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_messagetext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertelegram',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usertelegram',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usertelegram',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='usertelegram',
            name='education_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertelegram',
            name='education_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertelegram',
            name='remind_interval',
            field=models.IntegerField(default=86400),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст пользователя'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='name',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='Никнейм пользователя'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='sex',
            field=models.BooleanField(blank=True, null=True, verbose_name='Пол (Мужской-1, Женский-0) пользователя'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='tg_id',
            field=models.IntegerField(verbose_name='Уникальный ИД телеграмма'),
        ),
    ]
