# Generated by Django 4.0.4 on 2022-06-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_usertelegram_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertelegram',
            name='course_name',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='Название курса'),
        ),
    ]
